module.exports = {
    CHOOSE_USER_FROM_CLIENT: 'CHOOSE_USER_FROM_CLIENT',
    CHOOSE_USER_FROM_SERVER: 'CHOOSE_USER_FROM_SERVER',
    ADD_MESSAGE_FROM_CLIENT: 'ADD_MESSAGE_FROM_CLIENT',
    ADD_MESSAGE_FROM_SERVER: 'ADD_MESSAGE_FROM_SERVER',
    ENABLE_USER_FROM_SERVER: 'ENABLE_USER_FROM_SERVER',
}